version: 2.1
orbs:
  architect: giantswarm/architect@5.0.0

jobs:
  unit-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make test-unit
  integration-tests:
    executor: architect/machine
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - architect/machine-install-go
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/bin/docker-compose
      - run:
          name: "Run integration tests"
          command: |
            CGO_ENABLED=0 make test-integration
  acceptance-tests:
    executor: architect/machine
    machine:
      image: 'ubuntu-2004:2023.04.2'
    steps:
      - checkout
      - architect/machine-install-go
      - architect/integration-test-install-tools:
          apptestctl-version: v0.18.0
          helm-version: v3.13.3
          kubernetes-version: v1.25.0
      - run:
          name: "Run acceptance tests"
          command: CGO_ENABLED=0 make test-acceptance

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - unit-tests:
          filters:
            tags:
              only: /^v.*/

      - integration-tests:
          filters:
            tags:
              only: /^v.*/

      - acceptance-tests:
          filters:
            tags:
              only: /^v.*/

      - architect/go-build:
          context: architect
          name: go-build
          binary: aws-resolver-rules-operator
          resource_class: xlarge
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
            - unit-tests
            - integration-tests
            - acceptance-tests
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "aws-resolver-rules-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "aws-resolver-rules-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
