version: 2.1
orbs:
  architect: giantswarm/architect@4.33.0

jobs:
  unit-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make test-unit
  integration-tests:
    executor: architect/machine
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - architect/machine-install-go
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/bin/docker-compose
      - run:
          name: "Run integration tests"
          command: |
            CGO_ENABLED=0 make test-integration

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - unit-tests:
          filters:
            tags:
              only: /^v.*/

      - integration-tests:
          filters:
            tags:
              only: /^v.*/

      - architect/go-build:
          context: architect
          name: go-build
          binary: aws-resolver-rules-operator
          resource_class: xlarge
          requires:
            - unit-tests
            - integration-tests
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-aws-resolver-rules-operator-to-quay
          image: "quay.io/giantswarm/aws-resolver-rules-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
          - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-aws-resolver-rules-operator-to-docker
          image: "docker.io/giantswarm/aws-resolver-rules-operator"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
          - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "aws-resolver-rules-operator"
          requires:
          - push-aws-resolver-rules-operator-to-quay
          - push-aws-resolver-rules-operator-to-docker
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "aws-resolver-rules-operator"
          app_collection_repo: "capa-app-collection"
          requires:
          - push-aws-resolver-rules-operator-to-docker
          - push-aws-resolver-rules-operator-to-quay
          - push-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
