// Code generated by counterfeiter. DO NOT EDIT.
package resolverfakes

import (
	"context"
	"sync"

	"github.com/aws-resolver-rules-operator/pkg/resolver"
	"github.com/go-logr/logr"
)

type FakeRAMClient struct {
	CreateResourceShareWithContextStub        func(context.Context, string, bool, []string, []string) (string, error)
	createResourceShareWithContextMutex       sync.RWMutex
	createResourceShareWithContextArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 bool
		arg4 []string
		arg5 []string
	}
	createResourceShareWithContextReturns struct {
		result1 string
		result2 error
	}
	createResourceShareWithContextReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DeleteResourceShareWithContextStub        func(context.Context, logr.Logger, string) error
	deleteResourceShareWithContextMutex       sync.RWMutex
	deleteResourceShareWithContextArgsForCall []struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 string
	}
	deleteResourceShareWithContextReturns struct {
		result1 error
	}
	deleteResourceShareWithContextReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRAMClient) CreateResourceShareWithContext(arg1 context.Context, arg2 string, arg3 bool, arg4 []string, arg5 []string) (string, error) {
	var arg4Copy []string
	if arg4 != nil {
		arg4Copy = make([]string, len(arg4))
		copy(arg4Copy, arg4)
	}
	var arg5Copy []string
	if arg5 != nil {
		arg5Copy = make([]string, len(arg5))
		copy(arg5Copy, arg5)
	}
	fake.createResourceShareWithContextMutex.Lock()
	ret, specificReturn := fake.createResourceShareWithContextReturnsOnCall[len(fake.createResourceShareWithContextArgsForCall)]
	fake.createResourceShareWithContextArgsForCall = append(fake.createResourceShareWithContextArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 bool
		arg4 []string
		arg5 []string
	}{arg1, arg2, arg3, arg4Copy, arg5Copy})
	stub := fake.CreateResourceShareWithContextStub
	fakeReturns := fake.createResourceShareWithContextReturns
	fake.recordInvocation("CreateResourceShareWithContext", []interface{}{arg1, arg2, arg3, arg4Copy, arg5Copy})
	fake.createResourceShareWithContextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRAMClient) CreateResourceShareWithContextCallCount() int {
	fake.createResourceShareWithContextMutex.RLock()
	defer fake.createResourceShareWithContextMutex.RUnlock()
	return len(fake.createResourceShareWithContextArgsForCall)
}

func (fake *FakeRAMClient) CreateResourceShareWithContextCalls(stub func(context.Context, string, bool, []string, []string) (string, error)) {
	fake.createResourceShareWithContextMutex.Lock()
	defer fake.createResourceShareWithContextMutex.Unlock()
	fake.CreateResourceShareWithContextStub = stub
}

func (fake *FakeRAMClient) CreateResourceShareWithContextArgsForCall(i int) (context.Context, string, bool, []string, []string) {
	fake.createResourceShareWithContextMutex.RLock()
	defer fake.createResourceShareWithContextMutex.RUnlock()
	argsForCall := fake.createResourceShareWithContextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeRAMClient) CreateResourceShareWithContextReturns(result1 string, result2 error) {
	fake.createResourceShareWithContextMutex.Lock()
	defer fake.createResourceShareWithContextMutex.Unlock()
	fake.CreateResourceShareWithContextStub = nil
	fake.createResourceShareWithContextReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeRAMClient) CreateResourceShareWithContextReturnsOnCall(i int, result1 string, result2 error) {
	fake.createResourceShareWithContextMutex.Lock()
	defer fake.createResourceShareWithContextMutex.Unlock()
	fake.CreateResourceShareWithContextStub = nil
	if fake.createResourceShareWithContextReturnsOnCall == nil {
		fake.createResourceShareWithContextReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createResourceShareWithContextReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeRAMClient) DeleteResourceShareWithContext(arg1 context.Context, arg2 logr.Logger, arg3 string) error {
	fake.deleteResourceShareWithContextMutex.Lock()
	ret, specificReturn := fake.deleteResourceShareWithContextReturnsOnCall[len(fake.deleteResourceShareWithContextArgsForCall)]
	fake.deleteResourceShareWithContextArgsForCall = append(fake.deleteResourceShareWithContextArgsForCall, struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.DeleteResourceShareWithContextStub
	fakeReturns := fake.deleteResourceShareWithContextReturns
	fake.recordInvocation("DeleteResourceShareWithContext", []interface{}{arg1, arg2, arg3})
	fake.deleteResourceShareWithContextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRAMClient) DeleteResourceShareWithContextCallCount() int {
	fake.deleteResourceShareWithContextMutex.RLock()
	defer fake.deleteResourceShareWithContextMutex.RUnlock()
	return len(fake.deleteResourceShareWithContextArgsForCall)
}

func (fake *FakeRAMClient) DeleteResourceShareWithContextCalls(stub func(context.Context, logr.Logger, string) error) {
	fake.deleteResourceShareWithContextMutex.Lock()
	defer fake.deleteResourceShareWithContextMutex.Unlock()
	fake.DeleteResourceShareWithContextStub = stub
}

func (fake *FakeRAMClient) DeleteResourceShareWithContextArgsForCall(i int) (context.Context, logr.Logger, string) {
	fake.deleteResourceShareWithContextMutex.RLock()
	defer fake.deleteResourceShareWithContextMutex.RUnlock()
	argsForCall := fake.deleteResourceShareWithContextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRAMClient) DeleteResourceShareWithContextReturns(result1 error) {
	fake.deleteResourceShareWithContextMutex.Lock()
	defer fake.deleteResourceShareWithContextMutex.Unlock()
	fake.DeleteResourceShareWithContextStub = nil
	fake.deleteResourceShareWithContextReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRAMClient) DeleteResourceShareWithContextReturnsOnCall(i int, result1 error) {
	fake.deleteResourceShareWithContextMutex.Lock()
	defer fake.deleteResourceShareWithContextMutex.Unlock()
	fake.DeleteResourceShareWithContextStub = nil
	if fake.deleteResourceShareWithContextReturnsOnCall == nil {
		fake.deleteResourceShareWithContextReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteResourceShareWithContextReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRAMClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createResourceShareWithContextMutex.RLock()
	defer fake.createResourceShareWithContextMutex.RUnlock()
	fake.deleteResourceShareWithContextMutex.RLock()
	defer fake.deleteResourceShareWithContextMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRAMClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resolver.RAMClient = new(FakeRAMClient)
