// Code generated by counterfeiter. DO NOT EDIT.
package resolverfakes

import (
	"context"
	"sync"

	"github.com/aws-resolver-rules-operator/pkg/resolver"
)

type FakeResolverClient struct {
	AssociateResolverRuleWithContextStub        func(context.Context, string, string, string) error
	associateResolverRuleWithContextMutex       sync.RWMutex
	associateResolverRuleWithContextArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	associateResolverRuleWithContextReturns struct {
		result1 error
	}
	associateResolverRuleWithContextReturnsOnCall map[int]struct {
		result1 error
	}
	CreateResolverRuleStub        func(context.Context, resolver.Cluster, string, string, string) (string, string, error)
	createResolverRuleMutex       sync.RWMutex
	createResolverRuleArgsForCall []struct {
		arg1 context.Context
		arg2 resolver.Cluster
		arg3 string
		arg4 string
		arg5 string
	}
	createResolverRuleReturns struct {
		result1 string
		result2 string
		result3 error
	}
	createResolverRuleReturnsOnCall map[int]struct {
		result1 string
		result2 string
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeResolverClient) AssociateResolverRuleWithContext(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.associateResolverRuleWithContextMutex.Lock()
	ret, specificReturn := fake.associateResolverRuleWithContextReturnsOnCall[len(fake.associateResolverRuleWithContextArgsForCall)]
	fake.associateResolverRuleWithContextArgsForCall = append(fake.associateResolverRuleWithContextArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.AssociateResolverRuleWithContextStub
	fakeReturns := fake.associateResolverRuleWithContextReturns
	fake.recordInvocation("AssociateResolverRuleWithContext", []interface{}{arg1, arg2, arg3, arg4})
	fake.associateResolverRuleWithContextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeResolverClient) AssociateResolverRuleWithContextCallCount() int {
	fake.associateResolverRuleWithContextMutex.RLock()
	defer fake.associateResolverRuleWithContextMutex.RUnlock()
	return len(fake.associateResolverRuleWithContextArgsForCall)
}

func (fake *FakeResolverClient) AssociateResolverRuleWithContextCalls(stub func(context.Context, string, string, string) error) {
	fake.associateResolverRuleWithContextMutex.Lock()
	defer fake.associateResolverRuleWithContextMutex.Unlock()
	fake.AssociateResolverRuleWithContextStub = stub
}

func (fake *FakeResolverClient) AssociateResolverRuleWithContextArgsForCall(i int) (context.Context, string, string, string) {
	fake.associateResolverRuleWithContextMutex.RLock()
	defer fake.associateResolverRuleWithContextMutex.RUnlock()
	argsForCall := fake.associateResolverRuleWithContextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeResolverClient) AssociateResolverRuleWithContextReturns(result1 error) {
	fake.associateResolverRuleWithContextMutex.Lock()
	defer fake.associateResolverRuleWithContextMutex.Unlock()
	fake.AssociateResolverRuleWithContextStub = nil
	fake.associateResolverRuleWithContextReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeResolverClient) AssociateResolverRuleWithContextReturnsOnCall(i int, result1 error) {
	fake.associateResolverRuleWithContextMutex.Lock()
	defer fake.associateResolverRuleWithContextMutex.Unlock()
	fake.AssociateResolverRuleWithContextStub = nil
	if fake.associateResolverRuleWithContextReturnsOnCall == nil {
		fake.associateResolverRuleWithContextReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.associateResolverRuleWithContextReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeResolverClient) CreateResolverRule(arg1 context.Context, arg2 resolver.Cluster, arg3 string, arg4 string, arg5 string) (string, string, error) {
	fake.createResolverRuleMutex.Lock()
	ret, specificReturn := fake.createResolverRuleReturnsOnCall[len(fake.createResolverRuleArgsForCall)]
	fake.createResolverRuleArgsForCall = append(fake.createResolverRuleArgsForCall, struct {
		arg1 context.Context
		arg2 resolver.Cluster
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.CreateResolverRuleStub
	fakeReturns := fake.createResolverRuleReturns
	fake.recordInvocation("CreateResolverRule", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.createResolverRuleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeResolverClient) CreateResolverRuleCallCount() int {
	fake.createResolverRuleMutex.RLock()
	defer fake.createResolverRuleMutex.RUnlock()
	return len(fake.createResolverRuleArgsForCall)
}

func (fake *FakeResolverClient) CreateResolverRuleCalls(stub func(context.Context, resolver.Cluster, string, string, string) (string, string, error)) {
	fake.createResolverRuleMutex.Lock()
	defer fake.createResolverRuleMutex.Unlock()
	fake.CreateResolverRuleStub = stub
}

func (fake *FakeResolverClient) CreateResolverRuleArgsForCall(i int) (context.Context, resolver.Cluster, string, string, string) {
	fake.createResolverRuleMutex.RLock()
	defer fake.createResolverRuleMutex.RUnlock()
	argsForCall := fake.createResolverRuleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeResolverClient) CreateResolverRuleReturns(result1 string, result2 string, result3 error) {
	fake.createResolverRuleMutex.Lock()
	defer fake.createResolverRuleMutex.Unlock()
	fake.CreateResolverRuleStub = nil
	fake.createResolverRuleReturns = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeResolverClient) CreateResolverRuleReturnsOnCall(i int, result1 string, result2 string, result3 error) {
	fake.createResolverRuleMutex.Lock()
	defer fake.createResolverRuleMutex.Unlock()
	fake.CreateResolverRuleStub = nil
	if fake.createResolverRuleReturnsOnCall == nil {
		fake.createResolverRuleReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
			result3 error
		})
	}
	fake.createResolverRuleReturnsOnCall[i] = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeResolverClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.associateResolverRuleWithContextMutex.RLock()
	defer fake.associateResolverRuleWithContextMutex.RUnlock()
	fake.createResolverRuleMutex.RLock()
	defer fake.createResolverRuleMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeResolverClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resolver.ResolverClient = new(FakeResolverClient)
