// Code generated by counterfeiter. DO NOT EDIT.
package resolverfakes

import (
	"context"
	"sync"

	"github.com/aws-resolver-rules-operator/pkg/resolver"
	"github.com/go-logr/logr"
)

type FakeEC2Client struct {
	CreateSecurityGroupForResolverEndpointsStub        func(context.Context, string, string, map[string]string) (string, error)
	createSecurityGroupForResolverEndpointsMutex       sync.RWMutex
	createSecurityGroupForResolverEndpointsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 map[string]string
	}
	createSecurityGroupForResolverEndpointsReturns struct {
		result1 string
		result2 error
	}
	createSecurityGroupForResolverEndpointsReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DeleteSecurityGroupForResolverEndpointsStub        func(context.Context, logr.Logger, string, string) error
	deleteSecurityGroupForResolverEndpointsMutex       sync.RWMutex
	deleteSecurityGroupForResolverEndpointsArgsForCall []struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 string
		arg4 string
	}
	deleteSecurityGroupForResolverEndpointsReturns struct {
		result1 error
	}
	deleteSecurityGroupForResolverEndpointsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEC2Client) CreateSecurityGroupForResolverEndpoints(arg1 context.Context, arg2 string, arg3 string, arg4 map[string]string) (string, error) {
	fake.createSecurityGroupForResolverEndpointsMutex.Lock()
	ret, specificReturn := fake.createSecurityGroupForResolverEndpointsReturnsOnCall[len(fake.createSecurityGroupForResolverEndpointsArgsForCall)]
	fake.createSecurityGroupForResolverEndpointsArgsForCall = append(fake.createSecurityGroupForResolverEndpointsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 map[string]string
	}{arg1, arg2, arg3, arg4})
	stub := fake.CreateSecurityGroupForResolverEndpointsStub
	fakeReturns := fake.createSecurityGroupForResolverEndpointsReturns
	fake.recordInvocation("CreateSecurityGroupForResolverEndpoints", []interface{}{arg1, arg2, arg3, arg4})
	fake.createSecurityGroupForResolverEndpointsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeEC2Client) CreateSecurityGroupForResolverEndpointsCallCount() int {
	fake.createSecurityGroupForResolverEndpointsMutex.RLock()
	defer fake.createSecurityGroupForResolverEndpointsMutex.RUnlock()
	return len(fake.createSecurityGroupForResolverEndpointsArgsForCall)
}

func (fake *FakeEC2Client) CreateSecurityGroupForResolverEndpointsCalls(stub func(context.Context, string, string, map[string]string) (string, error)) {
	fake.createSecurityGroupForResolverEndpointsMutex.Lock()
	defer fake.createSecurityGroupForResolverEndpointsMutex.Unlock()
	fake.CreateSecurityGroupForResolverEndpointsStub = stub
}

func (fake *FakeEC2Client) CreateSecurityGroupForResolverEndpointsArgsForCall(i int) (context.Context, string, string, map[string]string) {
	fake.createSecurityGroupForResolverEndpointsMutex.RLock()
	defer fake.createSecurityGroupForResolverEndpointsMutex.RUnlock()
	argsForCall := fake.createSecurityGroupForResolverEndpointsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeEC2Client) CreateSecurityGroupForResolverEndpointsReturns(result1 string, result2 error) {
	fake.createSecurityGroupForResolverEndpointsMutex.Lock()
	defer fake.createSecurityGroupForResolverEndpointsMutex.Unlock()
	fake.CreateSecurityGroupForResolverEndpointsStub = nil
	fake.createSecurityGroupForResolverEndpointsReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeEC2Client) CreateSecurityGroupForResolverEndpointsReturnsOnCall(i int, result1 string, result2 error) {
	fake.createSecurityGroupForResolverEndpointsMutex.Lock()
	defer fake.createSecurityGroupForResolverEndpointsMutex.Unlock()
	fake.CreateSecurityGroupForResolverEndpointsStub = nil
	if fake.createSecurityGroupForResolverEndpointsReturnsOnCall == nil {
		fake.createSecurityGroupForResolverEndpointsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createSecurityGroupForResolverEndpointsReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeEC2Client) DeleteSecurityGroupForResolverEndpoints(arg1 context.Context, arg2 logr.Logger, arg3 string, arg4 string) error {
	fake.deleteSecurityGroupForResolverEndpointsMutex.Lock()
	ret, specificReturn := fake.deleteSecurityGroupForResolverEndpointsReturnsOnCall[len(fake.deleteSecurityGroupForResolverEndpointsArgsForCall)]
	fake.deleteSecurityGroupForResolverEndpointsArgsForCall = append(fake.deleteSecurityGroupForResolverEndpointsArgsForCall, struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.DeleteSecurityGroupForResolverEndpointsStub
	fakeReturns := fake.deleteSecurityGroupForResolverEndpointsReturns
	fake.recordInvocation("DeleteSecurityGroupForResolverEndpoints", []interface{}{arg1, arg2, arg3, arg4})
	fake.deleteSecurityGroupForResolverEndpointsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeEC2Client) DeleteSecurityGroupForResolverEndpointsCallCount() int {
	fake.deleteSecurityGroupForResolverEndpointsMutex.RLock()
	defer fake.deleteSecurityGroupForResolverEndpointsMutex.RUnlock()
	return len(fake.deleteSecurityGroupForResolverEndpointsArgsForCall)
}

func (fake *FakeEC2Client) DeleteSecurityGroupForResolverEndpointsCalls(stub func(context.Context, logr.Logger, string, string) error) {
	fake.deleteSecurityGroupForResolverEndpointsMutex.Lock()
	defer fake.deleteSecurityGroupForResolverEndpointsMutex.Unlock()
	fake.DeleteSecurityGroupForResolverEndpointsStub = stub
}

func (fake *FakeEC2Client) DeleteSecurityGroupForResolverEndpointsArgsForCall(i int) (context.Context, logr.Logger, string, string) {
	fake.deleteSecurityGroupForResolverEndpointsMutex.RLock()
	defer fake.deleteSecurityGroupForResolverEndpointsMutex.RUnlock()
	argsForCall := fake.deleteSecurityGroupForResolverEndpointsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeEC2Client) DeleteSecurityGroupForResolverEndpointsReturns(result1 error) {
	fake.deleteSecurityGroupForResolverEndpointsMutex.Lock()
	defer fake.deleteSecurityGroupForResolverEndpointsMutex.Unlock()
	fake.DeleteSecurityGroupForResolverEndpointsStub = nil
	fake.deleteSecurityGroupForResolverEndpointsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeEC2Client) DeleteSecurityGroupForResolverEndpointsReturnsOnCall(i int, result1 error) {
	fake.deleteSecurityGroupForResolverEndpointsMutex.Lock()
	defer fake.deleteSecurityGroupForResolverEndpointsMutex.Unlock()
	fake.DeleteSecurityGroupForResolverEndpointsStub = nil
	if fake.deleteSecurityGroupForResolverEndpointsReturnsOnCall == nil {
		fake.deleteSecurityGroupForResolverEndpointsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteSecurityGroupForResolverEndpointsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeEC2Client) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createSecurityGroupForResolverEndpointsMutex.RLock()
	defer fake.createSecurityGroupForResolverEndpointsMutex.RUnlock()
	fake.deleteSecurityGroupForResolverEndpointsMutex.RLock()
	defer fake.deleteSecurityGroupForResolverEndpointsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEC2Client) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resolver.EC2Client = new(FakeEC2Client)
